service: task-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET

plugins:
  - serverless-offline